# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[MaxLFSR]]
git-tree-sha1 = "a9b2f13bbace459a0a9f4f7facada2361946aadf"
repo-rev = "master"
repo-url = "https://github.com/hildebrandmw/MaxLFSR.jl"
uuid = "baf6eaea-5535-433e-9234-5dfb57c28f99"
version = "0.1.0"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[SIMD]]
deps = ["InteractiveUtils"]
git-tree-sha1 = "603b6513b60a87574f77616ac4b0c9b206afaf58"
uuid = "fdea26ae-647d-5447-a871-4b548cad5224"
version = "2.8.0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"
